name: Integration Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          # - PHP_VERSION: php73-fpm
          #   MAGENTO_VERSION: 2.3.6-p1
          # - PHP_VERSION: php73-fpm
          #   MAGENTO_VERSION: 2.4.2
          # - PHP_VERSION: php74-fpm
          #   MAGENTO_VERSION: 2.4.2
          - PHP_VERSION: php81-fpm
            MAGENTO_VERSION: 2.4.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: PHP_VERSION=${{ matrix.PHP_VERSION }} MAGENTO_VERSION=magento${{ matrix.MAGENTO_VERSION }} docker-compose -f .github/workflows/templates/docker-compose.yml up -d

      # - name: Create branch for Composer and remove version from composer.json
        # run: git checkout -b feature/ci && sed -i '/version/d' ./composer.json

      - name: Enable developer mode
        run: docker exec m2 php bin/magento deploy:mode:set developer
        
      - name: DI compile
        run: docker exec m2 php bin/magento setup:di:compile

      - name: Run tests
        run: docker exec m2 /data/vendor/bin/phpunit -c /data/app/code/Buckaroo/Analytics/Test/etc/phpunit-integration.xml
